### PR TITLE
adding updates to sponsors, partners, and special thanks

### PR DESCRIPTION
**Pull request by eparubrub**
- moving sponsors up
- creating a contact section

### CODE REVIEW

**Review by tellaho — CHANGES_REQUESTED** [review]
Only bit of feedback is we should probably shift the organizers list to the bottom. Well, second to last above the Contact section.
- It helps with the visual rhythm a bit (not a random text block breaking up the images)
- Feels like the right prioritization, from like a... idk, priority perspective.

Just tested it out, this is what it would look like:
image

**Comment by tellaho** [comment]
This is non-blocking feedback but there's a "style" that we ought to start talking about when it comes to React components. Right now we're adding **_configuration_** to individual components, whereas a better strategy (i.e. for long-term maintenance) is to allow **_composition_** of child components within larger components.

This article talks about it a bit, but yeah. Bumbai, not necessary we refactor now. https://johno.com/composition-over-configuration

**Comment by eparubrub** [comment]
> Only bit of feedback is we should probably shift the organizers list to the bottom. Well, second to last above the Contact section.
> 
> * It helps with the visual rhythm a bit (not a random text block breaking up the images)
> * Feels like the right prioritization, from like a... idk, priority perspective.
> 
> Just tested it out, this is what it would look like: image

agreed, I had a hunch to move it down, I think I just needed a second confirmation to check the prioritization still felt right. Just added the correction in the last commit

**Comment by eparubrub** [comment]
> This is non-blocking feedback but there's a "style" that we ought to start talking about when it comes to React components. Right now we're adding **_configuration_** to individual components, whereas a better strategy (i.e. for long-term maintenance) is to allow **_composition_** of child components within larger components.
> 
> This article talks about it a bit, but yeah. Bumbai, not necessary we refactor now. https://johno.com/composition-over-configuration

agreed*, these recent configuration commits felt like band-aid solutions and not sustainable long-term so yea definitely down to talk about it and go over some solutions in the future. I'm not as familiar with how we would handle composition within components.

**Review by tellaho — APPROVED** [review]

**Pull request merged**
